export const COUNTRY_REGIONS = {
  Afghanistan: { region: "Asia", subregion: "Southern Asia" },
  Albania: { region: "Europe", subregion: "Southern Europe" },
  Algeria: { region: "Africa", subregion: "Northern Africa" },
  Andorra: { region: "Europe", subregion: "Southern Europe" },
  Angola: { region: "Africa", subregion: "Sub-Saharan Africa" },
  "Antigua and Barbuda": { region: "Americas", subregion: "Caribbean" },
  Argentina: { region: "Americas", subregion: "South America" },
  Armenia: { region: "Asia", subregion: "Western Asia" },
  Australia: { region: "Oceania", subregion: "Australia and New Zealand" },
  Austria: { region: "Europe", subregion: "Western Europe" },
  Azerbaijan: { region: "Asia", subregion: "Western Asia" },
  Bahamas: { region: "Americas", subregion: "Caribbean" },
  Bahrain: { region: "Asia", subregion: "Western Asia" },
  Bangladesh: { region: "Asia", subregion: "Southern Asia" },
  Barbados: { region: "Americas", subregion: "Caribbean" },
  Belarus: { region: "Europe", subregion: "Eastern Europe" },
  Belgium: { region: "Europe", subregion: "Western Europe" },
  Belize: { region: "Americas", subregion: "Central America" },
  Benin: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Bhutan: { region: "Asia", subregion: "Southern Asia" },
  Bolivia: { region: "Americas", subregion: "South America" },
  "Bosnia and Herzegovina": { region: "Europe", subregion: "Southern Europe" },
  Botswana: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Brazil: { region: "Americas", subregion: "South America" },
  Brunei: { region: "Asia", subregion: "South-Eastern Asia" },
  Bulgaria: { region: "Europe", subregion: "Eastern Europe" },
  "Burkina Faso": { region: "Africa", subregion: "Sub-Saharan Africa" },
  Burundi: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Cambodia: { region: "Asia", subregion: "South-Eastern Asia" },
  Cameroon: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Canada: { region: "Americas", subregion: "Northern America" },
  "Central African Republic": {
    region: "Africa",
    subregion: "Sub-Saharan Africa",
  },
  Chad: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Chile: { region: "Americas", subregion: "South America" },
  China: { region: "Asia", subregion: "Eastern Asia" },
  Colombia: { region: "Americas", subregion: "South America" },
  Comoros: { region: "Africa", subregion: "Sub-Saharan Africa" },
  "Costa Rica": { region: "Americas", subregion: "Central America" },
  "Côte d'Ivoire": { region: "Africa", subregion: "Sub-Saharan Africa" },
  Croatia: { region: "Europe", subregion: "Southern Europe" },
  Cuba: { region: "Americas", subregion: "Caribbean" },
  Cyprus: { region: "Asia", subregion: "Western Asia" },
  "Czech Republic": { region: "Europe", subregion: "Eastern Europe" },
  Denmark: { region: "Europe", subregion: "Northern Europe" },
  Djibouti: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Dominica: { region: "Americas", subregion: "Caribbean" },
  "Dominican Republic": { region: "Americas", subregion: "Caribbean" },
  Ecuador: { region: "Americas", subregion: "South America" },
  Egypt: { region: "Africa", subregion: "Northern Africa" },
  "El Salvador": { region: "Americas", subregion: "Central America" },
  "Equatorial Guinea": { region: "Africa", subregion: "Sub-Saharan Africa" },
  Eritrea: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Estonia: { region: "Europe", subregion: "Northern Europe" },
  Eswatini: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Ethiopia: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Fiji: { region: "Oceania", subregion: "Melanesia" },
  Finland: { region: "Europe", subregion: "Northern Europe" },
  France: { region: "Europe", subregion: "Western Europe" },
  Gabon: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Gambia: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Georgia: { region: "Asia", subregion: "Western Asia" },
  Germany: { region: "Europe", subregion: "Western Europe" },
  Ghana: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Greece: { region: "Europe", subregion: "Southern Europe" },
  Grenada: { region: "Americas", subregion: "Caribbean" },
  Guatemala: { region: "Americas", subregion: "Central America" },
  Guinea: { region: "Africa", subregion: "Sub-Saharan Africa" },
  "Guinea-Bissau": { region: "Africa", subregion: "Sub-Saharan Africa" },
  Guyana: { region: "Americas", subregion: "South America" },
  Haiti: { region: "Americas", subregion: "Caribbean" },
  Honduras: { region: "Americas", subregion: "Central America" },
  Hungary: { region: "Europe", subregion: "Eastern Europe" },
  Iceland: { region: "Europe", subregion: "Northern Europe" },
  India: { region: "Asia", subregion: "Southern Asia" },
  Indonesia: { region: "Asia", subregion: "South-Eastern Asia" },
  Iran: { region: "Asia", subregion: "Southern Asia" },
  Iraq: { region: "Asia", subregion: "Western Asia" },
  Ireland: { region: "Europe", subregion: "Northern Europe" },
  Israel: { region: "Asia", subregion: "Western Asia" },
  Italy: { region: "Europe", subregion: "Southern Europe" },
  Jamaica: { region: "Americas", subregion: "Caribbean" },
  Japan: { region: "Asia", subregion: "Eastern Asia" },
  Jordan: { region: "Asia", subregion: "Western Asia" },
  Kazakhstan: { region: "Asia", subregion: "Central Asia" },
  Kenya: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Kiribati: { region: "Oceania", subregion: "Micronesia" },
  Kosovo: { region: "Europe", subregion: "Southern Europe" },
  Kuwait: { region: "Asia", subregion: "Western Asia" },
  Kyrgyzstan: { region: "Asia", subregion: "Central Asia" },
  Laos: { region: "Asia", subregion: "South-Eastern Asia" },
  Latvia: { region: "Europe", subregion: "Northern Europe" },
  Lebanon: { region: "Asia", subregion: "Western Asia" },
  Lesotho: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Liberia: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Libya: { region: "Africa", subregion: "Northern Africa" },
  Liechtenstein: { region: "Europe", subregion: "Western Europe" },
  Lithuania: { region: "Europe", subregion: "Northern Europe" },
  Luxembourg: { region: "Europe", subregion: "Western Europe" },
  Madagascar: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Malawi: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Malaysia: { region: "Asia", subregion: "South-Eastern Asia" },
  Maldives: { region: "Asia", subregion: "Southern Asia" },
  Mali: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Malta: { region: "Europe", subregion: "Southern Europe" },
  "Marshall Islands": { region: "Oceania", subregion: "Micronesia" },
  Mauritania: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Mauritius: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Mexico: { region: "Americas", subregion: "Central America" },
  Micronesia: { region: "Oceania", subregion: "Micronesia" },
  Moldova: { region: "Europe", subregion: "Eastern Europe" },
  Monaco: { region: "Europe", subregion: "Western Europe" },
  Mongolia: { region: "Asia", subregion: "Eastern Asia" },
  Montenegro: { region: "Europe", subregion: "Southern Europe" },
  Morocco: { region: "Africa", subregion: "Northern Africa" },
  Mozambique: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Myanmar: { region: "Asia", subregion: "South-Eastern Asia" },
  Namibia: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Nauru: { region: "Oceania", subregion: "Micronesia" },
  Nepal: { region: "Asia", subregion: "Southern Asia" },
  Netherlands: { region: "Europe", subregion: "Western Europe" },
  "New Zealand": { region: "Oceania", subregion: "Australia and New Zealand" },
  Nicaragua: { region: "Americas", subregion: "Central America" },
  Niger: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Nigeria: { region: "Africa", subregion: "Sub-Saharan Africa" },
  "North Korea": { region: "Asia", subregion: "Eastern Asia" },
  "North Macedonia": { region: "Europe", subregion: "Southern Europe" },
  Norway: { region: "Europe", subregion: "Northern Europe" },
  Oman: { region: "Asia", subregion: "Western Asia" },
  Pakistan: { region: "Asia", subregion: "Southern Asia" },
  Palau: { region: "Oceania", subregion: "Micronesia" },
  Panama: { region: "Americas", subregion: "Central America" },
  "Papua New Guinea": { region: "Oceania", subregion: "Melanesia" },
  Paraguay: { region: "Americas", subregion: "South America" },
  Peru: { region: "Americas", subregion: "South America" },
  Philippines: { region: "Asia", subregion: "South-Eastern Asia" },
  Poland: { region: "Europe", subregion: "Eastern Europe" },
  Portugal: { region: "Europe", subregion: "Southern Europe" },
  Qatar: { region: "Asia", subregion: "Western Asia" },
  Romania: { region: "Europe", subregion: "Eastern Europe" },
  Russia: { region: "Europe", subregion: "Eastern Europe" },
  Rwanda: { region: "Africa", subregion: "Sub-Saharan Africa" },
  "Saint Kitts and Nevis": { region: "Americas", subregion: "Caribbean" },
  "Saint Lucia": { region: "Americas", subregion: "Caribbean" },
  "Saint Vincent and the Grenadines": {
    region: "Americas",
    subregion: "Caribbean",
  },
  Samoa: { region: "Oceania", subregion: "Polynesia" },
  "San Marino": { region: "Europe", subregion: "Southern Europe" },
  "São Tomé and Príncipe": {
    region: "Africa",
    subregion: "Sub-Saharan Africa",
  },
  "Saudi Arabia": { region: "Asia", subregion: "Western Asia" },
  Senegal: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Serbia: { region: "Europe", subregion: "Southern Europe" },
  Seychelles: { region: "Africa", subregion: "Sub-Saharan Africa" },
  "Sierra Leone": { region: "Africa", subregion: "Sub-Saharan Africa" },
  Singapore: { region: "Asia", subregion: "South-Eastern Asia" },
  Slovakia: { region: "Europe", subregion: "Eastern Europe" },
  Slovenia: { region: "Europe", subregion: "Southern Europe" },
  "Solomon Islands": { region: "Oceania", subregion: "Melanesia" },
  Somalia: { region: "Africa", subregion: "Sub-Saharan Africa" },
  "South Africa": { region: "Africa", subregion: "Sub-Saharan Africa" },
  "South Korea": { region: "Asia", subregion: "Eastern Asia" },
  "South Sudan": { region: "Africa", subregion: "Sub-Saharan Africa" },
  Spain: { region: "Europe", subregion: "Southern Europe" },
  "Sri Lanka": { region: "Asia", subregion: "Southern Asia" },
  Sudan: { region: "Africa", subregion: "Northern Africa" },
  Suriname: { region: "Americas", subregion: "South America" },
  Sweden: { region: "Europe", subregion: "Northern Europe" },
  Switzerland: { region: "Europe", subregion: "Western Europe" },
  Syria: { region: "Asia", subregion: "Western Asia" },
  Tajikistan: { region: "Asia", subregion: "Central Asia" },
  Tanzania: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Thailand: { region: "Asia", subregion: "South-Eastern Asia" },
  "Timor-Leste": { region: "Asia", subregion: "South-Eastern Asia" },
  Togo: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Tonga: { region: "Oceania", subregion: "Polynesia" },
  "Trinidad and Tobago": { region: "Americas", subregion: "Caribbean" },
  Tunisia: { region: "Africa", subregion: "Northern Africa" },
  Turkey: { region: "Asia", subregion: "Western Asia" },
  Turkmenistan: { region: "Asia", subregion: "Central Asia" },
  Tuvalu: { region: "Oceania", subregion: "Polynesia" },
  Uganda: { region: "Africa", subregion: "Sub-Saharan Africa" },
  Ukraine: { region: "Europe", subregion: "Eastern Europe" },
  "United Arab Emirates": { region: "Asia", subregion: "Western Asia" },
  "United Kingdom": { region: "Europe", subregion: "Northern Europe" },
  "United States": { region: "Americas", subregion: "Northern America" },
  Uruguay: { region: "Americas", subregion: "South America" },
  Uzbekistan: { region: "Asia", subregion: "Central Asia" },
  Vanuatu: { region: "Oceania", subregion: "Melanesia" },
  "Vatican City": { region: "Europe", subregion: "Southern Europe" },
  Venezuela: { region: "Americas", subregion: "South America" },
  Vietnam: { region: "Asia", subregion: "South-Eastern Asia" },
  Yemen: { region: "Asia", subregion: "Western Asia" },
  Zambia: { region: "Africa", subregion: "Sub-Saharan Africa" },

  DEFAULT: { region: "Other", subregion: "Other" },
};

// Make clean country list (remove DEFAULT)
export const COUNTRIES = Object.keys(COUNTRY_REGIONS).filter(
  (c) => c !== "DEFAULT"
);

// Helper
export function getRegionData(country) {
  return COUNTRY_REGIONS[country] || COUNTRY_REGIONS.DEFAULT;
}
